use_frameworks!

platform :ios, '8.0'

source 'https://github.com/buvtopcc/CCSpecs.git'

target 'CCUtils_Example' do
  pod 'CCUtils', :path => '../'

  target 'CCUtils_Tests' do
    inherit! :search_paths

    
  end
end
